-- create tables

create table wky_group_of_goods (
    id                             number not null constraint wky_group_of_goods_id_pk primary key,
    row_version                    integer not null,
    group_number                   number,
    parent_group_number            number
                                   constraint wky_group_of_parent_group_fk
                                   references wky_group_of_goods on delete cascade,
    group_name                     varchar2(255),
    sorting_sequence               number,
    created                        date not null,
    created_by                     varchar2(255) not null,
    updated                        date not null,
    updated_by                     varchar2(255) not null
)
;



create or replace trigger wky_group_of_goods_biu
    before insert or update 
    on wky_group_of_goods
    for each row
begin
    if :new.id is null then
        :new.id := to_number(sys_guid(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX');
    end if;
    if inserting then
        :new.row_version := 1;
    elsif updating then
        :new.row_version := nvl(:old.row_version,0) + 1;
    end if;
    if inserting then
        :new.created := sysdate;
        :new.created_by := nvl(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := nvl(sys_context('APEX$SESSION','APP_USER'),user);
end wky_group_of_goods_biu;
/


create index wky_group_of_goods_i1 on wky_group_of_goods (parent_group_number);

-- comments
comment on table wky_group_of_goods is 'Warengrouppe';
-- load data
 
-- Generated by Quick SQL Tuesday April 17, 2018  13:29:00
 
/*
bill_of_materials [Tree of articles]
  ate_id /fk wky_articles /nn
  part_id /fk wky_articles /nn
  quantity num
  sorting_sequence num

group_of_goods [Warengrouppe]
  group_number 
  parent_group_number /fk group_of_goods
  group_name 
  sorting_sequence num

# settings = { prefix: "WKY", PK: "TRIG", auditCols: true, rowVersion: true, APEX: true }
*/

