-- drop objects
drop table wky_island_postalcodes cascade constraints;

-- create tables
create table wky_island_postalcodes (
    id                             number not null constraint wky_island_postalc_id_pk primary key,
    row_version                    integer not null,
    cty_id                         number
                                   constraint wky_island_postalc_cty_id_fk
                                   references wky_countries not null,
    start_postalcode               varchar2(10),
    end_postalcode                 varchar2(10),
    delivery_possible              varchar2(1) default on null 'N',
    created                        date not null,
    created_by                     varchar2(255) not null,
    updated                        date not null,
    updated_by                     varchar2(255) not null
)
;


-- triggers
create or replace trigger wky_island_postalcodes_biu
    before insert or update 
    on wky_island_postalcodes
    for each row
begin
    if :new.id is null then
        :new.id := to_number(sys_guid(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX');
    end if;
    if inserting then
        :new.row_version := 1;
    elsif updating then
        :new.row_version := nvl(:old.row_version,0) + 1;
    end if;
    if inserting then
        :new.created := sysdate;
        :new.created_by := nvl(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := nvl(sys_context('APEX$SESSION','APP_USER'),user);
end wky_island_postalcodes_biu;
/


-- indexes
create index wky_island_postalcodes_i1 on wky_island_postalcodes (cty_id);

-- comments
comment on table wky_island_postalcodes is 'IPE';
comment on column wky_island_postalcodes.cty_id is 'Foreign key to wky_countries table';
-- load data
 
-- Generated by Quick SQL Friday August 31, 2018  11:50:27
 
/*
island_postalcodes [IPE]
  cty_id /nn /fk wky_countries [Foreign key to wky_countries table]
  start_postalcode vc10
  end_postalcode vc10
  delivery_possible vc1 /default N

# settings = { prefix: "wky", onDelete: "RESTRICT", PK: "TRIG", auditCols: true, rowVersion: true, drop: true, language: "EN", APEX: true }
*/
