-- drop objects
--drop table wky_orders_potential_double cascade constraints;

-- create tables
create table wky_orders_potential_double (
    id                             number not null constraint wky_orders_potenti_id_pk primary key,
    row_version                    integer not null,
    new_odr_id                     number
                                   constraint wky_orders_pote_new_odr_id_unq unique
                                   constraint wky_orders_pote_new_odr_id_fk
                                   references wky_orders not null,
    existing_odr_id                number
                                   constraint wky_orders_po_existing_odr_fk
                                   references wky_orders not null,
    verified_flag                  varchar2(1) default on null 'N' not null,
    created                        date not null,
    created_by                     varchar2(255) not null,
    updated                        date not null,
    updated_by                     varchar2(255) not null
)
;


-- triggers
create or replace trigger wky_orders_potential_doubl
    before insert or update 
    on wky_orders_potential_double
    for each row
begin
    if :new.id is null then
        :new.id := to_number(sys_guid(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX');
    end if;
    if inserting then
        :new.row_version := 1;
    elsif updating then
        :new.row_version := nvl(:old.row_version,0) + 1;
    end if;
    if inserting then
        :new.created := sysdate;
        :new.created_by := nvl(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := nvl(sys_context('APEX$SESSION','APP_USER'),user);
end wky_orders_potential_doubl;
/


-- indexes
create index wky_orders_potential_double_i1 on wky_orders_potential_double (existing_odr_id);
create index wky_orders_potential_double_i2 on wky_orders_potential_double (new_odr_id);

-- comments
comment on table wky_orders_potential_double is 'OPE: Table registers potential double orders';
comment on column wky_orders_potential_double.verified_flag is 'Initially set to N and set to Y when the order is validated for double entry';

comment on column wky_orders.manual_added is 'Used for manually adding customers trough ORACLE kundencervice application';
 

-- load data
 
-- Generated by Quick SQL Monday August 27, 2018  08:11:23
 
/*
orders_potential_double [OPE: Table registers potential double orders]
  new_odr_id /nn /unique /fk wky_orders
  existing_odr_id /nn /fk wky_orders
  verified_flag vc1 /default N /nn [Initially set to N and set to Y when the order is validated for double entry]

# settings = { prefix: "wky", onDelete: "RESTRICT", PK: "TRIG", auditCols: true, rowVersion: true, drop: true, language: "EN", APEX: true }
*/
