-- create tables
create table wky_bill_of_materials (
    id                             number not null constraint wky_bill_of_materi_id_pk primary key,
    row_version                    integer not null,
    ate_id                         number
                                   constraint wky_bill_of_materi_ate_id_fk
                                   references wky_articles on delete cascade not null,
    part_id                        number
                                   constraint wky_bill_of_materi_part_id_fk
                                   references wky_articles on delete cascade not null,
    quantity                       number,
    sorting_sequence               number,
    created                        date not null,
    created_by                     varchar2(255) not null,
    updated                        date not null,
    updated_by                     varchar2(255) not null
)
;


-- triggers
create or replace trigger wky_bill_of_materials_biu
    before insert or update 
    on wky_bill_of_materials
    for each row
begin
    if :new.id is null then
        :new.id := to_number(sys_guid(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX');
    end if;
    if inserting then
        :new.row_version := 1;
    elsif updating then
        :new.row_version := nvl(:old.row_version,0) + 1;
    end if;
    if inserting then
        :new.created := sysdate;
        :new.created_by := nvl(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := nvl(sys_context('APEX$SESSION','APP_USER'),user);
end wky_bill_of_materials_biu;
/


-- indexes
create index wky_bill_of_materials_i1 on wky_bill_of_materials (ate_id);
create index wky_bill_of_materials_i2 on wky_bill_of_materials (part_id);

-- comments
comment on table wky_bill_of_materials is 'Tree of articles';
-- load data
 
-- Generated by Quick SQL Tuesday April 17, 2018  12:29:06
 
/*
bill_of_materials [Tree of articles]
  ate_id /fk wky_articles /nn
  part_id /fk wky_articles /nn
  quantity num
  sorting_sequence num

# settings = { prefix: "WKY", PK: "TRIG", auditCols: true, rowVersion: true, APEX: true }
*/

