--------------------------------------------------------
--  File created - woensdag-mei-23-2018   
--------------------------------------------------------
--select sysdate from dual;
---------------------------
--Changed TABLE
--INT_COMMON_LOGGING
---------------------------
ALTER TABLE "INT_COMMON_LOGGING" ADD CONSTRAINT "INT_IMP_AFTERBUY_ID_PK" PRIMARY KEY ("ID") ENABLE;

---------------------------
--New TABLE
--WKY_ZIPCODE_CARRIER_COSTS
---------------------------
  CREATE TABLE "WKY_ZIPCODE_CARRIER_COSTS" 
   (	"ID" NUMBER NOT NULL ENABLE,
	"ROW_VERSION" NUMBER(*,0) NOT NULL ENABLE,
	"START_DATE" DATE,
	"END_DATE" DATE,
	"ATE_ID" NUMBER,
	"CTY_ID" NUMBER,
	"POSTAL_CODE_FROM" VARCHAR2(10),
	"POSTAL_CODE_TO" VARCHAR2(10),
	"CRR_ID" NUMBER,
	"PRICE" NUMBER(22,10),
	"LXW_PK" NUMBER(22,10),
	"LXW_ACTION" VARCHAR2(20),
	"LXW_DATE" DATE,
	"CREATED" DATE NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(255) NOT NULL ENABLE,
	"UPDATED" DATE NOT NULL ENABLE,
	"UPDATED_BY" VARCHAR2(255) NOT NULL ENABLE,
	CONSTRAINT "WKY_ZIPCODE_CARRIE_ID_PK" PRIMARY KEY ("ID") ENABLE,
	CONSTRAINT "WKY_ZIPCODE_CARRIE_ATE_ID_FK" FOREIGN KEY ("ATE_ID")
	 REFERENCES "WKY_ARTICLES" ("ID") ENABLE,
	CONSTRAINT "WKY_ZIPCODE_CARRIE_CRR_ID_FK" FOREIGN KEY ("CRR_ID")
	 REFERENCES "WKY_CARRIERS" ("ID") ENABLE,
	CONSTRAINT "WKY_ZIPCODE_CARRIE_CTY_ID_FK" FOREIGN KEY ("CTY_ID")
	 REFERENCES "WKY_COUNTRIES" ("ID") ENABLE
   );
---------------------------
--Changed TABLE
--WKY_RETURN_REASONS_LKP
---------------------------
ALTER TABLE "WKY_RETURN_REASONS_LKP" MODIFY ("CREATED" NOT NULL ENABLE);
ALTER TABLE "WKY_RETURN_REASONS_LKP" MODIFY ("CREATED_BY" NOT NULL ENABLE);
ALTER TABLE "WKY_RETURN_REASONS_LKP" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "WKY_RETURN_REASONS_LKP" MODIFY ("LOOKUPCODE" NOT NULL ENABLE);
ALTER TABLE "WKY_RETURN_REASONS_LKP" MODIFY ("ROW_VERSION" NOT NULL ENABLE);
ALTER TABLE "WKY_RETURN_REASONS_LKP" MODIFY ("UPDATED" NOT NULL ENABLE);
ALTER TABLE "WKY_RETURN_REASONS_LKP" MODIFY ("UPDATED_BY" NOT NULL ENABLE);
ALTER TABLE "WKY_RETURN_REASONS_LKP" ADD CONSTRAINT "WKY_RETURN_REASONS_ID_PK" PRIMARY KEY ("ID") ENABLE;

---------------------------
--Changed TABLE
--WKY_PROFORMAACCOUNTS
---------------------------
ALTER TABLE "WKY_PROFORMAACCOUNTS" DROP ("ACT_ID");
ALTER TABLE "WKY_PROFORMAACCOUNTS" DROP ("BOR_ID");
ALTER TABLE "WKY_PROFORMAACCOUNTS" DROP CONSTRAINT "WKY_PROFORMAACCOUN_ACT_ID_FK";
ALTER TABLE "WKY_PROFORMAACCOUNTS" DROP CONSTRAINT "WKY_PROFORMAACCOUN_BOR_ID_FK";

---------------------------
--Changed TABLE
--WKY_PACKAGES
---------------------------
ALTER TABLE "WKY_PACKAGES" ADD ("AIRWAY_BILL_NUMBER" VARCHAR2(100));
ALTER TABLE "WKY_PACKAGES" ADD ("COLLI_NR" NUMBER(22,5));
ALTER TABLE "WKY_PACKAGES" ADD ("LABEL" VARCHAR2(4000));
ALTER TABLE "WKY_PACKAGES" ADD ("ODR_ID" NUMBER);
ALTER TABLE "WKY_PACKAGES" ADD ("SCANNED" NUMBER(22,1));
ALTER TABLE "WKY_PACKAGES" ADD ("VOLUME" NUMBER(22,3));
ALTER TABLE "WKY_PACKAGES" ADD ("WEIGHT" NUMBER(22,5));

---------------------------
--Changed TABLE
--WKY_ORDERS
---------------------------
ALTER TABLE "WKY_ORDERS" ADD ("DELIVERY_DATE" DATE);
ALTER TABLE "WKY_ORDERS" ADD ("FOOTER_TEXT" VARCHAR2(4000));
ALTER TABLE "WKY_ORDERS" ADD ("GROUP_OF_GOODS" VARCHAR2(4000 CHAR));
ALTER TABLE "WKY_ORDERS" ADD ("HEADER_TEXT" VARCHAR2(4000));
ALTER TABLE "WKY_ORDERS" ADD ("LXW_BESTELLNR" VARCHAR2(120 CHAR));
ALTER TABLE "WKY_ORDERS" ADD ("ORDER_COMMENT" VARCHAR2(4000));
ALTER TABLE "WKY_ORDERS" ADD ("ORDER_PARENT_ID" NUMBER);
ALTER TABLE "WKY_ORDERS" ADD ("ORDER_SOURCE" VARCHAR2(20 CHAR));
ALTER TABLE "WKY_ORDERS" ADD ("SHIPPING_DATE" DATE);
ALTER TABLE "WKY_ORDERS" ADD CONSTRAINT "WKY_ORDERS_ODR_ID_FK" FOREIGN KEY ("ORDER_PARENT_ID") REFERENCES "WKY_ORDERS"("ID") ENABLE;

---------------------------
--New TABLE
--WKY_MAIL_LOGS
---------------------------
  CREATE TABLE "WKY_MAIL_LOGS" 
   (	"ID" NUMBER NOT NULL ENABLE,
	"ROW_VERSION" NUMBER(*,0) NOT NULL ENABLE,
	"ODR_ID" NUMBER NOT NULL ENABLE,
	"MHL_ID" NUMBER NOT NULL ENABLE,
	"DATE_SENT" DATE NOT NULL ENABLE,
	"CREATED" DATE NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(255) NOT NULL ENABLE,
	"UPDATED" DATE NOT NULL ENABLE,
	"UPDATED_BY" VARCHAR2(255) NOT NULL ENABLE,
	"USER_ID" NUMBER NOT NULL ENABLE,
	CONSTRAINT "WKY_MAIL_LOGS_ID_PK" PRIMARY KEY ("ID") ENABLE,
	CONSTRAINT "WKY_MAIL_LOGS_FK1" FOREIGN KEY ("USER_ID")
	 REFERENCES "WKY_USER" ("ID") ENABLE,
	CONSTRAINT "WKY_MAIL_LOGS_MHL_ID_FK" FOREIGN KEY ("MHL_ID")
	 REFERENCES "WKY_MAIL_HTMLEMAILS" ("ID") ENABLE,
	CONSTRAINT "WKY_MAIL_LOGS_ODR_ID_FK" FOREIGN KEY ("ODR_ID")
	 REFERENCES "WKY_ORDERS" ("ID") ENABLE
   );
---------------------------
--Changed TABLE
--WKY_MAIL_HTMLEMAILS
---------------------------
ALTER TABLE "WKY_MAIL_HTMLEMAILS" ADD ("LXW_ACTION" VARCHAR2(20));
ALTER TABLE "WKY_MAIL_HTMLEMAILS" ADD ("LXW_DATE" DATE);
ALTER TABLE "WKY_MAIL_HTMLEMAILS" ADD ("MSS_ID" NUMBER);
ALTER TABLE "WKY_MAIL_HTMLEMAILS" DROP ("STATUS");

---------------------------
--New TABLE
--WKY_COUNTRY_CARRIER_COSTS
---------------------------
  CREATE TABLE "WKY_COUNTRY_CARRIER_COSTS" 
   (	"ID" NUMBER NOT NULL ENABLE,
	"ROW_VERSION" NUMBER(*,0) NOT NULL ENABLE,
	"START_DATE" DATE,
	"END_DATE" DATE,
	"ATE_ID" NUMBER,
	"CTY_ID" NUMBER,
	"CRR_ID" NUMBER,
	"PRICE" NUMBER(22,10),
	"LXW_PK" NUMBER(22,10),
	"LXW_ACTION" VARCHAR2(20),
	"LXW_DATE" DATE,
	"CREATED" DATE NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(255) NOT NULL ENABLE,
	"UPDATED" DATE NOT NULL ENABLE,
	"UPDATED_BY" VARCHAR2(255) NOT NULL ENABLE,
	CONSTRAINT "WKY_COUNTRY_CARRIE_ID_PK" PRIMARY KEY ("ID") ENABLE,
	CONSTRAINT "WKY_COUNTRY_CARRIE_ATE_ID_FK" FOREIGN KEY ("ATE_ID")
	 REFERENCES "WKY_ARTICLES" ("ID") ENABLE,
	CONSTRAINT "WKY_COUNTRY_CARRIE_CRR_ID_FK" FOREIGN KEY ("CRR_ID")
	 REFERENCES "WKY_CARRIERS" ("ID") ENABLE,
	CONSTRAINT "WKY_COUNTRY_CARRIE_CTY_ID_FK" FOREIGN KEY ("CTY_ID")
	 REFERENCES "WKY_COUNTRIES" ("ID") ENABLE
   );
---------------------------
--Changed TABLE
--WKY_CONTACT_TYPES_LKP
---------------------------
ALTER TABLE "WKY_CONTACT_TYPES_LKP" MODIFY ("CREATED" NOT NULL ENABLE);
ALTER TABLE "WKY_CONTACT_TYPES_LKP" MODIFY ("CREATED_BY" NOT NULL ENABLE);
ALTER TABLE "WKY_CONTACT_TYPES_LKP" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "WKY_CONTACT_TYPES_LKP" MODIFY ("LOOKUPCODE" NOT NULL ENABLE);
ALTER TABLE "WKY_CONTACT_TYPES_LKP" MODIFY ("ROW_VERSION" NOT NULL ENABLE);
ALTER TABLE "WKY_CONTACT_TYPES_LKP" MODIFY ("UPDATED" NOT NULL ENABLE);
ALTER TABLE "WKY_CONTACT_TYPES_LKP" MODIFY ("UPDATED_BY" NOT NULL ENABLE);
ALTER TABLE "WKY_CONTACT_TYPES_LKP" ADD CONSTRAINT "WKY_CONTACT_TYPES_ID_PK" PRIMARY KEY ("ID") ENABLE;

---------------------------
--Changed TABLE
--WKY_COMPLAINTS
---------------------------
ALTER TABLE "WKY_COMPLAINTS" ADD ("CRR_ID" NUMBER);
ALTER TABLE "WKY_COMPLAINTS" ADD ("CTS_ID" NUMBER);
ALTER TABLE "WKY_COMPLAINTS" ADD ("CT_TYPE" VARCHAR2(1));
ALTER TABLE "WKY_COMPLAINTS" ADD ("REFOUND_MONEY" VARCHAR2(1));
ALTER TABLE "WKY_COMPLAINTS" ADD ("TURN_ON_BILL" VARCHAR2(1));
ALTER TABLE "WKY_COMPLAINTS" ADD CONSTRAINT "WKY_COMPLAINTS_CRR_ID_FK" FOREIGN KEY ("CRR_ID") REFERENCES "WKY_RETURN_REASONS_LKP"("ID") ENABLE;
ALTER TABLE "WKY_COMPLAINTS" ADD CONSTRAINT "WKY_COMPLAINTS_FK1" FOREIGN KEY ("CTS_ID") REFERENCES "WKY_CONTACT_TYPES_LKP"("ID") ENABLE;

---------------------------
--Changed TABLE
--WKY_COMPLAINT_REASONS_LKP
---------------------------
ALTER TABLE "WKY_COMPLAINT_REASONS_LKP" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "WKY_COMPLAINT_REASONS_LKP" ADD CONSTRAINT "WKY_COMPLAINT_REASONS_LKP_PK" PRIMARY KEY ("ID") ENABLE;

---------------------------
--Changed TABLE
--WKY_COMPLAINTCONCERNINGARTICLE
---------------------------
ALTER TABLE "WKY_COMPLAINTCONCERNINGARTICLE" ADD ("AMOUNT" NUMBER);
ALTER TABLE "WKY_COMPLAINTCONCERNINGARTICLE" ADD ("ARTICLE_NAME" VARCHAR2(200));
ALTER TABLE "WKY_COMPLAINTCONCERNINGARTICLE" ADD ("CTR_ID" NUMBER);
ALTER TABLE "WKY_COMPLAINTCONCERNINGARTICLE" MODIFY ("STATUS" VARCHAR2(1 CHAR) DEFAULT 'A');
ALTER TABLE "WKY_COMPLAINTCONCERNINGARTICLE" ADD CONSTRAINT "WKY_COMPLAINTARTICLERES_FK1" FOREIGN KEY ("CTR_ID") REFERENCES "WKY_COMPLAINT_REASONS_LKP"("ID") ENABLE;

---------------------------
--Changed TABLE
--WKY_CARRIERS
---------------------------
ALTER TABLE "WKY_CARRIERS" ADD ("BROKER" VARCHAR2(1));
ALTER TABLE "WKY_CARRIERS" ADD ("CARRIERCODE" VARCHAR2(3));
ALTER TABLE "WKY_CARRIERS" ADD ("LXW_ACTION" VARCHAR2(20));
ALTER TABLE "WKY_CARRIERS" ADD ("LXW_DATE" DATE);
ALTER TABLE "WKY_CARRIERS" ADD ("LXW_PK" NUMBER(22,10));
ALTER TABLE "WKY_CARRIERS" ADD ("SERVICELEVEL_TIME" VARCHAR2(20));

---------------------------
--Changed TABLE
--WKY_CARGOPLACE
---------------------------
ALTER TABLE "WKY_CARGOPLACE" ADD ("COLLECTION_DATE" DATE);
ALTER TABLE "WKY_CARGOPLACE" ADD ("COLLECTION_TIME" DATE);
ALTER TABLE "WKY_CARGOPLACE" ADD ("CRR_ID" NUMBER);
ALTER TABLE "WKY_CARGOPLACE" ADD ("DATE_CREATED" DATE);
ALTER TABLE "WKY_CARGOPLACE" ADD ("DAY" NUMBER(22,10));
ALTER TABLE "WKY_CARGOPLACE" ADD ("LXW_ACTION" VARCHAR2(20));
ALTER TABLE "WKY_CARGOPLACE" ADD ("LXW_DATE" DATE);
ALTER TABLE "WKY_CARGOPLACE" ADD ("LXW_PK" NUMBER(22,10));
ALTER TABLE "WKY_CARGOPLACE" ADD ("PICKS" NUMBER(22,10));
ALTER TABLE "WKY_CARGOPLACE" ADD ("PICKS_PAL" NUMBER(22,10));
ALTER TABLE "WKY_CARGOPLACE" ADD ("PICKS_PFP" NUMBER(22,10));
ALTER TABLE "WKY_CARGOPLACE" ADD ("PRICE" NUMBER(22,10));
ALTER TABLE "WKY_CARGOPLACE" MODIFY ("CARGOPLACENUMBER" NULL);
ALTER TABLE "WKY_CARGOPLACE" MODIFY ("HEIGHT" NULL);
ALTER TABLE "WKY_CARGOPLACE" MODIFY ("LENGTH" NULL);
ALTER TABLE "WKY_CARGOPLACE" MODIFY ("WIDTH" NULL);
ALTER TABLE "WKY_CARGOPLACE" MODIFY ("YEAR" NULL);
ALTER TABLE "WKY_CARGOPLACE" ADD CONSTRAINT "WKY_CARGOPLACE_CRR_ID_FK" FOREIGN KEY ("CRR_ID") REFERENCES "WKY_CARRIERS"("ID") ENABLE;

---------------------------
--Changed TABLE
--WKY_BILL_OF_MATERIALS
---------------------------
ALTER TABLE "WKY_BILL_OF_MATERIALS" MODIFY ("ATE_ID" NOT NULL ENABLE);
ALTER TABLE "WKY_BILL_OF_MATERIALS" MODIFY ("CREATED" NOT NULL ENABLE);
ALTER TABLE "WKY_BILL_OF_MATERIALS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
ALTER TABLE "WKY_BILL_OF_MATERIALS" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "WKY_BILL_OF_MATERIALS" MODIFY ("PART_ID" NOT NULL ENABLE);
ALTER TABLE "WKY_BILL_OF_MATERIALS" MODIFY ("ROW_VERSION" NOT NULL ENABLE);
ALTER TABLE "WKY_BILL_OF_MATERIALS" MODIFY ("UPDATED" NOT NULL ENABLE);
ALTER TABLE "WKY_BILL_OF_MATERIALS" MODIFY ("UPDATED_BY" NOT NULL ENABLE);
ALTER TABLE "WKY_BILL_OF_MATERIALS" ADD CONSTRAINT "WKY_BILL_OF_MATERI_ID_PK" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "WKY_BILL_OF_MATERIALS" ADD CONSTRAINT "WKY_BILL_OF_MATERI_ATE_ID_FK" FOREIGN KEY ("ATE_ID") REFERENCES "WKY_ARTICLES"("ID") ON DELETE CASCADE DISABLE;
ALTER TABLE "WKY_BILL_OF_MATERIALS" ADD CONSTRAINT "WKY_BILL_OF_MATERI_PART_ID_FK" FOREIGN KEY ("PART_ID") REFERENCES "WKY_ARTICLES"("ID") ON DELETE CASCADE DISABLE;

---------------------------
--Changed TABLE
--WKY_ARTICLES
---------------------------
ALTER TABLE "WKY_ARTICLES" ADD ("ARTICLENUMBER_VC2" VARCHAR2(100));

---------------------------
--Changed TABLE
--WKY_ACCOUNTS
---------------------------
ALTER TABLE "WKY_ACCOUNTS" ADD ("AMOUNTOFREFUND" NUMBER(22,2) NOT NULL ENABLE);
ALTER TABLE "WKY_ACCOUNTS" ADD ("CPT_ID" NUMBER);
ALTER TABLE "WKY_ACCOUNTS" ADD ("CRY_ID" NUMBER);
ALTER TABLE "WKY_ACCOUNTS" ADD ("DATEOFREFUND" DATE NOT NULL ENABLE);
ALTER TABLE "WKY_ACCOUNTS" ADD ("INVOICE_NUMBER" VARCHAR2(40));
ALTER TABLE "WKY_ACCOUNTS" ADD ("LXW_ACTION" VARCHAR2(20));
ALTER TABLE "WKY_ACCOUNTS" ADD ("LXW_DATE" DATE);
ALTER TABLE "WKY_ACCOUNTS" ADD ("LXW_PK" NUMBER(22,10));
ALTER TABLE "WKY_ACCOUNTS" ADD ("SCL_ID" NUMBER);
ALTER TABLE "WKY_ACCOUNTS" MODIFY ("ODR_ID" NULL);
ALTER TABLE "WKY_ACCOUNTS" DROP CONSTRAINT "WKY_ACCOUNTS_ODR_ID_FK";
ALTER TABLE "WKY_ACCOUNTS" ADD CONSTRAINT "WKY_ACCOUNTS_CPT_ID_FK" FOREIGN KEY ("CPT_ID") REFERENCES "WKY_COMPLAINTS"("ID") ENABLE;
ALTER TABLE "WKY_ACCOUNTS" ADD CONSTRAINT "WKY_ACCOUNTS_CRY_ID_FK" FOREIGN KEY ("CRY_ID") REFERENCES "WKY_CURRENCIES"("ID") ENABLE;
ALTER TABLE "WKY_ACCOUNTS" ADD CONSTRAINT "WKY_ACCOUNTS_ODR_ID_FK" FOREIGN KEY ("ODR_ID") REFERENCES "WKY_ORDERS"("ID") ENABLE;
ALTER TABLE "WKY_ACCOUNTS" ADD CONSTRAINT "WKY_ACCOUNTS_SCL_ID_FK" FOREIGN KEY ("SCL_ID") REFERENCES "WKY_SALESCHANNELS"("ID") ENABLE;

