-- drop objects
drop table wky_eec_countries cascade constraints;

-- create tables
create table wky_eec_countries (
    id                             number not null constraint wky_eec_countries_id_pk primary key,
    row_version                    integer not null,
    cty_id                         number
                                   constraint wky_eec_countries_cty_id_fk
                                   references wky_countries not null,
    start_date                     date not null,
    end_date                       date,
    eec_flag                       varchar2(1) not null,
    created                        date not null,
    created_by                     varchar2(255) not null,
    updated                        date not null,
    updated_by                     varchar2(255) not null
)
;


-- triggers
create or replace trigger wky_eec_countries_biu
    before insert or update 
    on wky_eec_countries
    for each row
begin
    if :new.id is null then
        :new.id := to_number(sys_guid(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX');
    end if;
    if inserting then
        :new.row_version := 1;
    elsif updating then
        :new.row_version := nvl(:old.row_version,0) + 1;
    end if;
    if inserting then
        :new.created := sysdate;
        :new.created_by := nvl(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := nvl(sys_context('APEX$SESSION','APP_USER'),user);
end wky_eec_countries_biu;
/


-- indexes
create index wky_eec_countries_i1 on wky_eec_countries (cty_id);

-- comments
comment on table wky_eec_countries is 'ECY: identifies if country is in or not in the EEC';
-- load data
 
-- Generated by Quick SQL Thursday August 23, 2018  13:42:00
 
/*
eec_countries [ECY: identifies if country is in or not in the EEC]
  cty_id /fk wky_countries /nn
  start_date /nn
  end_date
  eec_flag vc1 /nn

# settings = { prefix: "wky", onDelete: "RESTRICT", PK: "TRIG", auditCols: true, rowVersion: true, drop: true, language: "EN", APEX: true }
*/


/*Views*/
-- current EEC Countries
drop view wky_current_eec_countries;

create or replace force view wky_current_eec_countries_v
as
select cty.*
     , ecy.eec_flag, ecy.start_date, ecy.end_date
  from wky_countries cty
     , wky_eec_countries ecy 
 where cty.id = ecy.cty_id(+)
   and nvl( ecy.eec_flag, 'Y') = 'Y'
   and sysdate between nvl( ecy.start_date, sysdate) and nvl( ecy.end_date, sysdate)
 ;
 
-- Current Non-EEC Countries
drop view wky_current_noneec_countries;

create or replace force view wky_current_noneec_countries_v
as
select cty.*
     , ecy.eec_flag, ecy.start_date, ecy.end_date
  from wky_countries cty
     , wky_eec_countries ecy 
 where cty.id = ecy.cty_id(+)
   and nvl( ecy.eec_flag, 'Y') = 'N'
   and sysdate between nvl( ecy.start_date, sysdate) and nvl( ecy.end_date, sysdate)
 ;