-- drop objects
--drop table wky_mail_statuses_lkp cascade constraints;

-- create tables
create table wky_mail_statuses_lkp (
    id                             number not null constraint wky_mail_statuses_id_pk primary key,
    row_version                    integer not null,
    lookupcode                     varchar2(50) not null,
    language                       varchar2(5) not null,
    lookupvalue                    varchar2(250),
    sortingsequence                number(22,10),
    active                         varchar2(1) default on null 'Y' not null,
    mapping_code                   varchar2(50),
    created                        date not null,
    created_by                     varchar2(255) not null,
    updated                        date not null,
    updated_by                     varchar2(255) not null
)
;


-- triggers
create or replace trigger wky_mail_statuses_lkp_biu
    before insert or update 
    on wky_mail_statuses_lkp
    for each row
begin
    if :new.id is null then
        :new.id := to_number(sys_guid(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX');
    end if;
    if inserting then
        :new.row_version := 1;
    elsif updating then
        :new.row_version := nvl(:old.row_version,0) + 1;
    end if;
    if inserting then
        :new.created := sysdate;
        :new.created_by := nvl(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := nvl(sys_context('APEX$SESSION','APP_USER'),user);
end wky_mail_statuses_lkp_biu;
/


-- comments
comment on table wky_mail_statuses_lkp is 'MSS'; 

-- load data
 
-- Generated by Quick SQL Wednesday April 25, 2018  08:00:27
 
/*
mail_statuses_lkp [MSS]
  lookupcode vc50 /nn
  language   vc5 /nn
  lookupvalue vc250
  sortingsequence num(22,10)
  active vc1 /nn /default Y
  mapping_code vc50

# settings = { prefix: "WKY", onDelete: "RESTRICT", PK: "TRIG", auditCols: true, rowVersion: true, drop: true, APEX: true }
*/


-- drop objects
drop table wky_complaint_actions_lkp cascade constraints;

-- create tables
create table wky_complaint_actions_lkp (
    id                             number not null constraint wky_complaint_acti_id_pk primary key,
    row_version                    integer not null,
    lookupcode                     varchar2(50) not null,
    language                       varchar2(5) not null,
    lookupvalue                    varchar2(250),
    sortingsequence                number(22,10),
    active                         varchar2(1) default on null 'Y' not null,
    mapping_code                   varchar2(50),
    created                        date not null,
    created_by                     varchar2(255) not null,
    updated                        date not null,
    updated_by                     varchar2(255) not null
)
;


-- triggers
create or replace trigger wky_complaint_actions_lkp_
    before insert or update 
    on wky_complaint_actions_lkp
    for each row
begin
    if :new.id is null then
        :new.id := to_number(sys_guid(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX');
    end if;
    if inserting then
        :new.row_version := 1;
    elsif updating then
        :new.row_version := nvl(:old.row_version,0) + 1;
    end if;
    if inserting then
        :new.created := sysdate;
        :new.created_by := nvl(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := nvl(sys_context('APEX$SESSION','APP_USER'),user);
end wky_complaint_actions_lkp_;
/


-- comments
comment on table wky_complaint_actions_lkp is 'CAN';
-- load data
 
-- Generated by Quick SQL Wednesday April 25, 2018  09:18:14
 
/*
complaint_actions_lkp [CAN]
  lookupcode vc50 /nn
  language   vc5 /nn
  lookupvalue vc250
  sortingsequence num(22,10)
  active vc1 /nn /default Y
  mapping_code vc50

# settings = { prefix: "WKY", onDelete: "RESTRICT", PK: "TRIG", auditCols: true, rowVersion: true, drop: true, APEX: true }
*/


-- drop objects
--drop table wky_ledger cascade constraints;

-- create tables
create table wky_ledger (
    id                             number not null constraint wky_ledger_id_pk primary key,
    row_version                    integer not null,
    odr_id                         number
                                   constraint wky_ledger_odr_id_fk
                                   references wky_orders not null,
    ust_set                        number(22),
    ust_total                      number(22),
    ust_account                    number(22),
    net_amount                     number(22),
    gross_amount                   number(22),
    lxw_id                         number,
    lxw_action                     varchar2(20),
    lxw_date                       date,
    created                        date not null,
    created_by                     varchar2(255) not null,
    updated                        date not null,
    updated_by                     varchar2(255) not null
)
;


-- triggers
create or replace trigger wky_ledger_biu
    before insert or update 
    on wky_ledger
    for each row
begin
    if :new.id is null then
        :new.id := to_number(sys_guid(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX');
    end if;
    if inserting then
        :new.row_version := 1;
    elsif updating then
        :new.row_version := nvl(:old.row_version,0) + 1;
    end if;
    if inserting then
        :new.created := sysdate;
        :new.created_by := nvl(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := nvl(sys_context('APEX$SESSION','APP_USER'),user);
end wky_ledger_biu;
/


comment on table wky_ledger is 'LGR';

-- indexes
create index wky_ledger_i1 on wky_ledger (odr_id);
-- load data

-- Generated by Quick SQL Wednesday April 25, 2018  10:25:17
 
/*
ledger [LGR]
  odr_id /nn /fk wky_orders
  ust_set num(22)
  ust_total num(22)
  ust_account num(22)
  net_amount num(22)
  gross_amount num(22)
  lxw_id num
  lxw_action vc20
  lxw_date date

# settings = { prefix: "WKY", onDelete: "RESTRICT", PK: "TRIG", auditCols: true, rowVersion: true, drop: true, APEX: true }
*/


